### ISSUE TITLE
Travis + databases = fun 

### ISSUE THREAD

**Issue by matthewdking** [fac-13/test-o#35]
So I have had problems with this in the past and struggled to find much in terms of documentation. There is a bit [here](https://docs.travis-ci.com/user/database-setup/).

I think essentially it comes down to adding this to your `travis.yml`
```yml
services:
  - postgresql
before_script:
  - psql -c 'create database patheighteentest;' -U postgres
```

There might be another step so if this doesn't work let me know.
